### ISSUE TITLE
반응형 페이지 구현

### ISSUE THREAD

**Issue by JOO05** [ProjectFRIDAY/Remoa-FE#12]
### 📝 Description
디바이스의 디스플레이의 종류에 반응하여 그에 맞도록 적절하게 요소들이 유기적으로 배치되도록 설계된 반응형 웹을 구현한다.

### 💻 Todo
- [ ] 반응형 헤더 제작
- [ ] 반응형 메인 페이지 제작 (기획/아이디어 레퍼런스 창)
- [ ] 기타 css 반응형으로 수정

### 💽 ETC
개발 완료 단계에 이르면 중간 정도 구현한 부분에서 추가적으로 구현할 예정이다. 다른 기능을 구현하는 것보다 긴급 순위가 낮다.
in progress에서 임시로 to do로 옮겼다.

### 🖼 결과
-
