### ISSUE TITLE
레퍼런스 페이지 모달 창 GUI 제작 작업 및 더미 데이터로 테스트

### ISSUE THREAD

**Issue by JOO05** [ProjectFRIDAY/Remoa-FE#21]
### 📝 Description
레퍼런스 페이지 모달 창 GUI 제작 작업 및 더미 데이터로 테스트한다. 백엔드와 연결하는 실제 기능 구현과는 별개이다. 대댓글 기능은 임시적으로 제외한다.

### 💻 Todo
- [ ] 전체 GUI 제작하기
- [x] 1:n 모달창 구현하기 (팔로워 팔로잉)
- [x] 실제 데이터베이스처럼 더미 데이터 넣어서 테스트하기
- [ ] 상세 피드백 모달창 제작

### 💽 ETC
기타사항

### 🖼 결과
-

![Image](https://user-images.githubusercontent.com/103393199/223086962-fd271836-3bd8-46a1-a934-5059bd2921e3.png)

![Image](https://user-images.githubusercontent.com/103393199/223086974-a5cdca05-931b-4071-bc1b-a3ed0f78b7f5.png)
