### ISSUE TITLE
헤더 제작 및 초안 기반 GUI 적용

### ISSUE THREAD

**Issue by JOO05** [ProjectFRIDAY/Remoa-FE#5]
### 📝 Description
figma를 토대로 한 UI/UX 정의서 중 헤더와 헤더를 클릭해 이동할 페이지의 GUI를 제작한다.
### 💻 Todo
- [x] 헤더 완성
- [x] 페이지 초안 제작
- [x] 드롭다운 메뉴의 역할을 할 페이지 내부의 세부 헤더를 제작하고 각 파트에 맞는 페이지 초안 제작
- [x] 헤더 및 페이지 내부 세부 헤더에 실제 페이지 링크 연결 작업
- [ ] 로그인 여부에 따라 달라지는 헤더의 GUI를 제작
- [ ] 가입 이메일 찾기 및 가입 비밀번호 찾기 GUI 제작

### 🖼 결과

![Image](https://user-images.githubusercontent.com/103393199/212880207-5b34df2b-0d67-4227-af4d-71cc632e4b8a.png)
